// src/lib/cms-image.ts
// Look up build-time optimized variants for CMS-hosted images
// (ari.icjia-api.cloud). Manifest is generated by scripts/fetch-cms-images.mjs
// during `npm run build`; everything in the manifest gets a WebP at
// /adultredeploy/_cms-img/<hash>-<width>.webp

import manifestData from './cms-image-manifest.json' with { type: 'json' };

interface Variant { w: number; src: string; }
interface Entry {
  width: number;
  height: number;
  variants: Variant[];
  largest: string;
}
type Manifest = Record<string, Entry>;

const manifest = manifestData as Manifest;

const BASE = import.meta.env?.BASE_URL ?? '/adultredeploy';

function withBase(p: string): string {
  // Variant srcs are stored as "/_cms-img/foo.webp"; prepend BASE_URL so they
  // resolve against the mounted prefix on prod.
  return p.startsWith('/') ? `${BASE}${p}` : p;
}

export interface CmsImage {
  src: string;
  srcset: string;
  width: number;
  height: number;
}

export function getCmsImage(originalUrl: string | null | undefined): CmsImage | null {
  if (!originalUrl) return null;
  const entry = manifest[originalUrl];
  if (!entry) return null;
  return {
    src: withBase(entry.largest),
    srcset: entry.variants.map((v) => `${withBase(v.src)} ${v.w}w`).join(', '),
    width: entry.width,
    height: entry.height,
  };
}

// Drop the http origin to look up the relative URL too (some templates pass
// a Strapi-relative `/uploads/foo.jpg`).
export function getCmsImageByPath(maybeUrl: string | null | undefined): CmsImage | null {
  if (!maybeUrl) return null;
  if (maybeUrl.startsWith('http')) return getCmsImage(maybeUrl);
  if (maybeUrl.startsWith('/uploads/')) {
    return getCmsImage(`https://ari.icjia-api.cloud${maybeUrl}`);
  }
  return null;
}
